#!/usr/bin/perl -w
#Usage: ./frMethylCorr.pl [minimumDepth] < sample_methylFreq.txt
#   sample_methylFreq.txt: the methylFreq file generated by bisReadMapper.pl

use strict;
use Statistics::LSNoHistory;
my %cpgTable;
my $minDepth = $ARGV[0];
$minDepth = 50 if (!$minDepth);
while(my $line = <STDIN>){
        my @fields = split(/\t/, $line);
        next if($fields[3] <$minDepth);
        my $chr = $fields[0];
        my $pos = $fields[1];
        my %alleleFreq;
        my $Fct;
	next if($fields[4] ne 'CG');
        for(my $i=5; $i<scalar(@fields); $i+=2){
                $alleleFreq{$fields[$i]}=$fields[$i+1];                 
                $Fct += $fields[$i+1] if($fields[$i]=~ /[CT]/);
        }
        next if (!$Fct || $Fct/$fields[3] < 0.9);
        my $methylLevel = sprintf("%3.2f", $alleleFreq{'C'}? $alleleFreq{'C'}/$Fct : 0);
        $cpgTable{$chr . ":" .$pos}->{$fields[2]}->{'methylFreq'}=$methylLevel;
        #$cpgTable{$chr . ":" .$pos}->{$fields[2]}->{'seqDepth'}=$fields[3];
}

my $corrStat = Statistics::LSNoHistory->new;
my $N=0;
foreach my $index (keys(%cpgTable)){
        if($cpgTable{$index}->{'W'} && $cpgTable{$index}->{'C'}){
			#print $index,"\t";			
			#print $cpgTable{$index}->{'W'}->{'methylFreq'}, "\t", $cpgTable{$index}->{'C'}->{'methylFreq'}, "\n";
			$corrStat->append_point($cpgTable{$index}->{'W'}->{'methylFreq'},$cpgTable{$index}->{'C'}->{'methylFreq'});		
			$N++;
        }
}
print  "N=$N\tr=", $corrStat->pearson_r,"\n"; 
